### ISSUE TITLE
How did you wire this?

### ISSUE THREAD

**Issue by 3dsf** [Amal-R-Jayakumar/Thermal-Camera-System#1]
I may have misunderstood -- are you using a I2C sensor with a UART interface?

**Comment by Amal-R-Jayakumar** [comment]
I'm using the MLX90640 thermal camera. It's more of an `I<sup>2</sup>C` Connection. The difference is URAT is a point-to-point connection while `I<sup>2</sup>C` is a bus of the same. You can get the full documentation at

**Comment by Amal-R-Jayakumar** [comment]
I'm using the MLX90640 thermal camera. It's more of an I2C Connection. The difference is URAT is a point-to-point connection while I2C is a bus of the same.

**Comment by Amal-R-Jayakumar** [comment]
There is a lot of documentation out there on how to get the output from this module.
